name: Streamlit Keep Alive

on:
schedule:
    # Her 6 saatte bir otomatik çalışır (Gece 00:00, 06:00, 12:00, 18:00)
    - cron: '0 */6 * * *'
  workflow_dispatch: # İstediğimiz zaman elle de çalıştırabilmek için

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Streamlit App
      run: curl -I https://tevsorgu.streamlit.app/
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Keep GitHub Repo Active
      run: |
        date > keep_alive.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keep_alive.txt
        git commit -m "Keep-alive update: $(date)"
        git push
