name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Streamlit App
      run: curl -I https://GUNCEL_SİTE_ADRESİN.streamlit.app

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Keep GitHub Repo Active
      run: |
        date > keep_alive.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keep_alive.txt
        git commit -m "Keep-alive update: $(date)"
        git push
